# Generated by Django 4.2.7 on 2023-11-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="price",
        ),
        migrations.RemoveField(
            model_name="book",
            name="title",
        ),
    ]
