# Generated by Django 4.2.7 on 2023-11-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_remove_book_price_remove_book_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="title",
            field=models.CharField(default="a", max_length=100),
            preserve_default=False,
        ),
    ]
